name: demolition
channels:
  - dlr-sc
  - projectchrono/label/develop
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.21.2
  - pandas=1.3.3
  - pychrono=6.0.0
  - pythonocc-core=7.4.1

#conda env update --file=environment.yml