name: demolition3
channels:
  - dlr-sc
  - projectchrono/label/develop
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - pychrono
  - pythonocc-core

#conda env update --file=environment.yml